### DISCUSSION TITLE
Script is not running with 10. addresses.

### DISCUSSION THREAD

**Discussion by Andre15711** [techno-tim/k3s-ansible#210] [Questions]
## Expected Behavior

during deployment an error occurred in k3s/master task

## Current Behavior
deployment stopped

## Steps to Reproduce

everytime.

## Context (variables)

all.yml

```yaml
---
k3s_version: v1.24.9+k3s1
# this is the user that has ssh access to these machines
ansible_user: ansible
systemd_dir: /etc/systemd/system

# Set your timezone
system_timezone: "Europe/Berlin"

# interface which will be used for flannel
flannel_iface: "eth0"

# apiserver_endpoint is virtual ip-address which will be configured on each master
apiserver_endpoint: "10.10.100.170"

# k3s_token is required  masters can talk together securely
# this token should be alpha numeric only
k3s_token: "xxx"

# The IP on which the node is reachable in the cluster.
# Here, a sensible default is provided, you can still override
# it for each of your hosts, though.
k3s_node_ip: '{{ ansible_facts[flannel_iface]["ipv4"]["address"] }}'

# Disable the taint manually by setting: k3s_master_taint = false
k3s_master_taint: "{{ true if groups['node'] | default([]) | length >= 1 else false }}"

# these arguments are recommended for servers as well as agents:
extra_args: >-
  --flannel-iface={{ flannel_iface }}
  --node-ip={{ k3s_node_ip }}

# change these to your liking, the only required are: --disable servicelb, --tls-san {{ apiserver_endpoint }}
extra_server_args: >-
  {{ extra_args }}
  {{ '--node-taint node-role.kubernetes.io/master=true:NoSchedule' if k3s_master_taint else '' }}
  --tls-san {{ apiserver_endpoint }}
  --disable servicelb
  --disable traefik
extra_agent_args: >-
  {{ extra_args }}

# image tag for kube-vip
kube_vip_tag_version: "v0.5.7"

# image tag for metal lb
metal_lb_speaker_tag_version: "v0.13.7"
metal_lb_controller_tag_version: "v0.13.7"

# metallb ip range for load balancer
metal_lb_ip_range: "10.10.100.80-10.10.100.89"
```

Operating system:
Ubuntu 22.04

Hardware:
VM

### Hosts

`host.ini`

```ini
[master]
10.10.100.171
10.10.100.172
10.10.100.173

[node]
10.10.100.174
10.10.100.175
10.10.100.176

[k3s_cluster:children]
master
node

```

## Possible Solution
I includes in the IP address fix int the script without variable. 

- [ x] I've checked the [General Troubleshooting Guide](https://github.com/techno-tim/k3s-ansible/discussions/20)

https://github.com/techno-tim/k3s-ansible/blob/e98e3ee77c7a07ed5ff1ab4588f394462c70b20f/roles/k3s/master/tasks/main.yml#L121
