### DISCUSSION TITLE
Disable swap

### DISCUSSION THREAD

**Discussion by dberardo-com** [techno-tim/k3s-ansible#267] [Questions] [answered]
I assume that swap needs to be disabled during installation:

ref why: https://github.com/k3s-io/k3s-ansible/issues/147

ref how to: https://germaniumhq.com/2019/02/14/2019-02-14-Disabling-Swap-for-Kubernetes-in-an-Ansible-Playbook/

**Comment by egandro** [comment]
Don't mess with this in k3s-ansible.

I have a preflight.yml and do whatever it requires in there. e.g. swap, enable/disable ipv6, install nfs-common, LANG to C.UTF-8, install ntp and htpdate (for fixing the clock after a VM restore), install qemu-guest-agent,

So you see there is plenty to do - totaly legit - but it is 1000% out of the scope of k3s-ansible.

**Comment by dberardo-com** [comment]
is the preflight optional in the procedure? i wonder why the swap hasnt been disabled in my case, maybe that was skipped ? can that be run on a already existing cluster?

**Comment by egandro** [comment]
Preflight is my own file I created.... (preflight.yml).

**Comment by egandro** [comment]
Check this: https://pastebin.com/3XPzSQfT

**Comment by ndragon798** [comment]
I would support adding an optional preflight list that could be enabled. It would make this a full solution for spinning up k3s aong with a os that supports cloud-init functionality.

**Comment by onedr0p** [comment, marked as answer]
Probably best to do it this way:

```yaml
        - name: System Configuration | Disable swap
          ansible.posix.mount:
            name: "{{ item }}"
            fstype: swap
            state: absent
          loop: ["none", "swap"]
```
