### DISCUSSION TITLE
Verify that all nodes actually joined - Debian

### DISCUSSION THREAD

**Discussion by fredrikscode** [techno-tim/k3s-ansible#54] [Questions] [answered]
## Expected Behavior
I run ansible-playbook site.yml -i inventory/k3s-cluster/hosts.ini and get a k3s-cluster deployed.

## Current Behavior
Runs through the playbook until the verification process which it goes through without success.

## Steps to Reproduce

1. Modify hosts.ini with ip's
2. Add variable to all.yml: `ansible_ssh_private_key_file: ~/.ssh/ansible`
3. Run site.yml using: `ansible-playbook site.yml -i inventory/k3s-cluster/hosts.ini`

## Context (variables)

Operating system: Debian 11

Hardware: (CPU/RAM/Disk type)
- Intel i5-8250U, 8GB, SSD
- Intel i3-9100, 64GB, SSD
- AMD Ryzen 5 PRO 1500, 24GB, SSD

### Variables Used:

`all.yml`
```yml
k3s_version: v1.24.3+k3s1
ansible_user: ansible
ansible_ssh_private_key_file: ~/.ssh/ansible
systemd_dir: /etc/systemd/system
system_timezone: "Europe/Stockholm"
flannel_iface: "eth0"
apiserver_endpoint: "10.0.0.100"
k3s_token: "strawberrycake"
extra_server_args: "--disable servicelb --disable traefik"
extra_agent_args: ""
kube_vip_tag_version: "v0.5.0"
metal_lb_speaker_tag_version: "v0.13.4"
metal_lb_controller_tag_version: "v0.13.4"
metal_lb_ip_range: "10.0.0.80-10.0.0.90"
```

### Hosts 

`host.ini`

```ini
[master]
k3s-master-01
k3s-master-02
k3s-master-03

[node]
k3s-worker-01
k3s-worker-02
k3s-worker-03

[k3s_cluster:children]
master
node
```
