### ISSUE TITLE
incorrectly validates setup on x86 hosts

### ISSUE THREAD

**Issue by yankeeinlondon** [techno-tim/k3s-ansible#15]
I have two physical Intel machines running Proxmox which have the following VMs:

- NUC i7
    - `plane-1` - _master_
    - `plane-3` - _master_
    - `worker-1` - _worker_
- Intel Denverton
    - `plane-2` - _master_
    - `worker-2` - _worker_

I run the ansible script from my Proxmox server and it fails on the **Verification** step (even after 20 attempts):
```yml
- name: Verification
  block:
    - name: Verify that all nodes actually joined (check k3s-init.service if this fails)
      command:
        cmd: k3s kubectl get nodes -l "node-role.kubernetes.io/master=true" -o=jsonpath="{.items[*].metadata.name}"
      register: nodes
      until: nodes.rc == 0 and (nodes.stdout.split() | length) == (groups['master'] | length)
      retries: 20
      delay: 10
      changed_when: false
```

I can stop the retry loop which ensures that the _transient_ process is not shut down by ansible and when I go into each of the three masters I can see that:

1. the transient process _is_ running
2. running `k3s kubectl get nodes` (of any variant) will fail as nothing is running on port 8080 which is why the above step fails

    <img width="559" alt="image" src="https://user-images.githubusercontent.com/980757/161614230-903c7a8f-ba29-4515-8397-5efa06cd9d98.png">

3. when you look for listeners on port 6443 the master VM's you'll find that indeed there is a service listening there:

    <img width="566" alt="image" src="https://user-images.githubusercontent.com/980757/161615318-e408b45a-4a68-4985-aea1-cf93e8850c20.png">

4. I have validated all k3s config files with `k3s check-config` and they are all fine
5. All files expected to copied to `/var/lib/rancher/k3s/server` have indeed been copied
    <img width="515" alt="image" src="https://user-images.githubusercontent.com/980757/161616362-967b8197-9cbf-4d13-8440-25204dcee3d8.png">

All of these were run with the base configuration in the repo but then I also tried removing the `extra_server_args` and `extra_agent_args` from `all.yml` but that seemed to have zero impact.
