### ISSUE TITLE
Handler reboot not found

### ISSUE THREAD

**Issue by RangersMS** [techno-tim/k3s-ansible#199]
## Expected Behavior

An handler called reboot executing a reboot after the task 'Activating group support' in `roles/raspberrypi/tasks/setup/Raspbian.yml` calls that handler. 

## Current Behavior
There is no handler 'reboot' with lowercase r but instead a handler called 'Reboot' with a capital letter in `roles/raspberrypi/handlers/main.yml`
`roles/raspberrypi/tasks/setup/Rocky.yml` and `roles/raspberrypi/tasks/setup/Ubuntu.yml` also call the handler reboot with lowercase r

The playbook fails at that point.
![SCR-20230107-sc1](https://user-images.githubusercontent.com/48658285/211167716-f1b451e8-8afd-4456-84b1-4d7b5521282b.png)

`roles/raspberrypi/handlers/main.yml`
```yml
---
- name: Reboot
  reboot:
```

## Steps to Reproduce

run `ansible-playbook site.yml -i inventory/mycluster/hosts.ini` against a Raspberry Pi. 

## Context (variables)

Operating system: MacOS and ansible was running inside a Docker container running ubuntu:22.04

Hardware: 1x Raspberry Pi 4 Model B 8GB

### Variables Used

`all.yml`

```yml
---
k3s_version: v1.24.9+k3s1
# this is the user that has ssh access to these machines
ansible_user: ansibleuser
systemd_dir: /etc/systemd/system

# Set your timezone
system_timezone: "UTC"

# interface which will be used for flannel
flannel_iface: "eth0"

# apiserver_endpoint is virtual ip-address which will be configured on each master
apiserver_endpoint: "192.168.25.200"

# k3s_token is required  masters can talk together securely
# this token should be alpha numeric only
k3s_token: "MySecretKeepsSecret"

# The IP on which the node is reachable in the cluster.
# Here, a sensible default is provided, you can still override
# it for each of your hosts, though.
k3s_node_ip: '{{ ansible_facts[flannel_iface]["ipv4"]["address"] }}'

# Disable the taint manually by setting: k3s_master_taint = false
k3s_master_taint: "{{ true if groups['node'] | default([]) | length >= 1 else false }}"

# these arguments are recommended for servers as well as agents:
extra_args: >-
  --flannel-iface={{ flannel_iface }}
  --node-ip={{ k3s_node_ip }}

# change these to your liking, the only required are: --disable servicelb, --tls-san {{ apiserver_endpoint }}
extra_server_args: >-
  {{ extra_args }}
  {{ '--node-taint node-role.kubernetes.io/master=true:NoSchedule' if k3s_master_taint else '' }}
  --tls-san {{ apiserver_endpoint }}
  --disable servicelb
  --disable traefik
extra_agent_args: >-
  {{ extra_args }}

# image tag for kube-vip
kube_vip_tag_version: "v0.5.7"

# image tag for metal lb
metal_lb_speaker_tag_version: "v0.13.7"
metal_lb_controller_tag_version: "v0.13.7"

# metallb ip range for load balancer
metal_lb_ip_range: "192.168.25.210-192.168.25.219"
```

### Hosts

`host.ini`

```ini
[master]
192.168.25.87 ansible_user=pi

[node]
192.168.25.87 ansible_user=pi

[k3s_cluster:children]
master
node

```

## Possible Solution

Rename the handler in `roles/raspberrypi/handlers/main.yml` to 'reboot' with a lowercase r. This worked for me. 

- [x] I've checked the [General Troubleshooting Guide](https://github.com/techno-tim/k3s-ansible/discussions/20)
