### ISSUE TITLE
Use in Proxmox VM with NIC VLAN

### ISSUE THREAD

**Issue by poxin13** [techno-tim/k3s-ansible#236]
## Expected Behavior

It may be a little out of the scope of the goal with this project, but here goes. I got everything setup and appears to be working except for remote network ingress to the example nginx. In my setup I have two nics on each of the VMs in proxmox (this might only be needed on the workers?). net0 provides an internal range like 192.168.1.0/24 and net1 is a VLAN that is for a range of external static IP addresses. The IP is assigned to nginx per the range that was setup in the ansible configuration, but it seems I'm not able to actually reach it. Wondering if anyone might have some insight or has a setup similar to this working.

```
Events:
  Type     Reason          Age                 From                Message
  ----     ------          ----                ----                -------
  Normal   IPAllocated     31m                 metallb-controller  Assigned IP ["EXTERNAL-IP"]
  Normal   nodeAssigned    31m                 metallb-speaker     announcing from node "k3s-worker-01" with protocol "layer2"
  Warning  announceFailed  16m (x9 over 16m)   metallb-speaker     the interfaces specified by LB IP "EXTERNAL-IP" doesn't exist in assigned node "k3s-worker-01" with protocol "layer2"
  Normal   nodeAssigned    12m (x3 over 14m)   metallb-speaker     announcing from node "k3s-node-01" with protocol "layer2"
  Normal   nodeAssigned    11m (x34 over 16m)  metallb-speaker     announcing from node "k3s-worker-01" with protocol "layer2"
```

```
/etc/netplan/00-installer-config.yaml 
# This is the network config written by 'subiquity'
network:
  ethernets:
    ens18:
      dhcp4: false
      addresses: [INTERNAL RANGE/16]
      routes:
        - to: default
          via: INTERNAL-GATEWAY
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
    ens19: {}
  vlans:
    vlan80:
      id: 80
      link: ens19
      addresses: [EXTERNAL-RANGE/24]
  version: 2
```

## Context (variables)

Operating system: Ubuntu 22.04

Hardware: Proxmox VM

- [X] I've checked the [General Troubleshooting Guide](https://github.com/techno-tim/k3s-ansible/discussions/20)
