### ISSUE TITLE
metallb fails a few minutes after it starts when flannel interface is wlan

### ISSUE THREAD

**Issue by mihai-dinculescu** [techno-tim/k3s-ansible#401]
When flannel interface is wlan, metallb fails a few minutes after it starts.

## Expected Behavior

LoadBalancer services work.

## Current Behavior

LoadBalancer services stop being reachable a few minutes after the cluster starts.

## Steps to Reproduce

1. ansible-playbook site.yml -i inventory/my-cluster/hosts.ini
2. Create an ingress or a LoadBalancer service
3. 
4.

## Context (variables)

Operating system:
Ubuntu Server 23.10

Hardware:
Raspberry Pi 5.

### Variables Used

`all.yml`

```yml
k3s_version: "v1.28.3+k3s1"
ansible_user: NA
systemd_dir: "/etc/systemd/system"

flannel_iface: "wlan0"

apiserver_endpoint: "192.168.1.190"

k3s_token: "NA"

extra_server_args: "no changes from master"
extra_agent_args: "no changes from master"

kube_vip_tag_version: "v0.5.12"

metal_lb_speaker_tag_version: "v0.13.9"
metal_lb_controller_tag_version: "v0.13.9"

metal_lb_ip_range: "192.168.1.210-192.168.1.220"
```

### Hosts

`host.ini`

```ini
[master]
io.local

[node]

[k3s_cluster:children]
master
node
```

## Possible Solution

Setting the wlan0 interface to work in promiscuous mode solves the issue.

```
sudo ifconfig wlan0 promisc
```

This setting is being lost on restart, so a `@reboot sudo ifconfig wlan0 promisc` is required as well.

- [x] I've checked the [General Troubleshooting Guide](https://github.com/techno-tim/k3s-ansible/discussions/20)
