### ISSUE TITLE
Hoping for any help on adding your code into my own playbook

### ISSUE THREAD

**Issue by Evantage-WS** [techno-tim/k3s-ansible#451]
Hi,

I do not know Ansible very well, but I have the collection installed with 
```
./collections/requirements.yml:

collections:
  - name: ansible.utils
  - name: community.general
  - name: ansible.posix
  - name: kubernetes.core
  - name: https://github.com/techno-tim/k3s-ansible.git
    type: git
    version: master
```
```
ansible-galaxy collection install -r ./collections/requirements.yml
```
and trying to use this in my own playbook.

I do have this yaml:

```
- name: Deploy K3s
  hosts: all
  become: true
  vars:
    k3s_version: v1.27.10+k3s2
    k3s_token: xcjkhudsf7y32jhdshfsd7asdasd3
    calico_iface: eth0
    apiserver_endpoint: 172.16.201.9
    k3s_master_taint: false
    kube_vip_lb_ip_range: 172.16.201.10-172.16.201.19

  collections:
    - techno_tim.k3s_ansible
  ```

is there a way to do this like this? I do see you are using site.yml, but I am unware how to use/import/call it in my own playbook. Could you be of help?

Thanks!
