### ISSUE TITLE
Ansible error using almost default values and metallb service LB

### ISSUE THREAD

**Issue by sharifm-informatica** [techno-tim/k3s-ansible#455]
## Expected Behavior
playbook would run and install

## Current Behavior
FATAL: FAILED! => {"msg": "The conditional check 'kube_vip_lb_ip_range is not defined and (not cilium_bgp or cilium_iface is not defined)' failed. The error was: error while evaluating conditional (kube_vip_lb_ip_range is not defined and (not cilium_bgp or cilium_iface is not defined)): 'cilium_bgp' is undefined. 'cilium_bgp' is undefined\n\nThe error appears to be in '/playbook/roles/k3s_server/tasks/main.yml': line 29, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Deploy metallb manifest\n  ^ here\n"}
## Steps to Reproduce

1. keep almost all groupvars at the default as per latest release
2. run the playbook 
3.
4.

## Context (variables)

Operating system:ubuntu server 22.04

Hardware:
VM
### Variables Used

`all.yml`

```yml
k3s_version: ""
ansible_user: NA
systemd_dir: ""

flannel_iface: ""

#calico_iface: ""
calico_ebpf: ""
calico_cidr: ""
calico_tag: ""

apiserver_endpoint: ""

k3s_token: "NA"

extra_server_args: ""
extra_agent_args: ""

kube_vip_tag_version: ""

kube_vip_cloud_provider_tag_version: ""
kube_vip_lb_ip_range: ""

metal_lb_speaker_tag_version: ""
metal_lb_controller_tag_version: ""

metal_lb_ip_range: ""
```

### Hosts

`host.ini`

```ini
[master]
IP.ADDRESS.ONE
IP.ADDRESS.TWO
IP.ADDRESS.THREE

[node]
IP.ADDRESS.FOUR
IP.ADDRESS.FIVE

[k3s_cluster:children]
master
node
```

## Possible Solution
1- change line 32 in `/roles/k3s_server/tasks/main.yml` to `when: kube_vip_lb_ip_range is not defined and (not cilium_bgp is not defined or cilium_iface is not defined)`

2- change line 15 in `/roles/k3s_server_post/tasks/main.yml` to `when: kube_vip_lb_ip_range is not defined and (not cilium_bgp is not defined or cilium_iface is not defined)`

I can submit a pull request if you think this solution is correct.
- [ x] I've checked the [General Troubleshooting Guide](https://github.com/techno-tim/k3s-ansible/discussions/20)
