### ISSUE TITLE
Cluster fails to survive reboot - Invalid IP assigned to node

### ISSUE THREAD

**Issue by Turtlez32** [techno-tim/k3s-ansible#461]
I have 2 clusters 
Production - 6 node (3 etcd, 3 worker)
Development -  3 node (3 etcd). 

Production is cloud-init backed Ubuntu 22.04 machines with static ip's set in cloud init. When building the cluster the first time its online and runs without issues. When I get a power outage or reboot. all nodes come back online but cluster is not available.

On reboot of production my nodes get ip's
1 - 10.0.99.2
1 - 10.0.99.2
1 - 10.0.99.2
1 - 10.0.99.2
1 - 10.0.99.2

## Expected Behavior

Cluster starts up without issues

## Current Behavior
Cluster is unable to start, restart required on all non first node to trigger IP move.

## Steps to Reproduce

1. Build a new k3s cluster based on the playbook
2. Define static IP address for each node (**Cloud-init/Netplan**)
3. Reboot cluster nodes
4. check ip a (second node gets first nodes IP with /32 subnet

## Context (variables)

Operating system: Ubuntu 22.04 | Debian 12
Hardware: Lenovo Tiny m900 (Production) | Lenovo Tiny M703 (Ubuntu 22.04 Server)

### Variables Used

`all.yml`

```yml
k3s_version: v1.29.0+k3s1
systemd_dir: /etc/systemd/system
system_timezone: "Australia/Sydney"
flannel_iface: "eth0"
apiserver_endpoint: "10.0.99.104"
k3s_node_ip: '{{ ansible_facts[flannel_iface]["ipv4"]["address"] }}'
k3s_master_taint: "{{ true if groups['node'] | default([]) | length >= 1 else false }}"

kube_vip_tag_version: "v0.6.4"
metal_lb_type: "native"
metal_lb_mode: "layer2"
metal_lb_speaker_tag_version: "v0.13.12"
metal_lb_controller_tag_version: "v0.13.12"
metal_lb_ip_range: "10.0.99.110-10.0.99.115"
```

### Hosts

`host.ini`

```ini
[master]
10.0.99.104
10.0.99.105
10.0.99.106

[k3s_cluster:children]
master
```

## Possible Solution
I am wondering if this is a cloud-init | proxmox | k3s issue. I am only seeing this issue on nodes 1/2 of my clusters. It started happening about 2 months ago when I was using Debian 12, saw there was a cloud-init bug about ip's. Switched to Ubuntu 22.04 and seeing the same issues.
