### ISSUE TITLE
Bump kube-vip to v0.7.1

### ISSUE THREAD

**Issue by yebo29** [techno-tim/k3s-ansible#464]
## Expected Behavior

We're running an outdated version of kube-vip. Are there any reasons _not_ to update to latest v0.7.1? I did so on my local system and nothing seems to have broken, but I haven't fully put it through its paces. There is one change on how it's deployed, however. The path to the RBAC manifest now lives at a different URL and not tied to a release tag. Will this cause issues in the future? I don't know enough about RBAC to know. I was thinking of opening a PR with my changes but wanted to post an issue first. 

I attempted the upgrade to see if it would fix an unrelated issue. While it did not fix the issue I was having, I do not fault kube-vip for it. I think the problem lies more with Litestream and how SQLite works.

I don't have a good reason to update kube-vip beyond just keeping things current. Nothing in the [changelogs](https://github.com/kube-vip/kube-vip/releases) jumped out at me. 

`v0.6.4 -> 0.7.0 -> 0.7.1`

## Current Behavior

Kube-vip on v0.6.4

## Steps to Reproduce

Not a bug; no steps to reproduce. 

## Context (variables)

Operating system: I've only tested on my local 3 node cluster running on Raspbian

Hardware: Pi4 Model B

### Variables Used

`all.yml`

```yml
k3s_version: "v1.29.0+k3s1"
ansible_user: NA
systemd_dir: "/etc/systemd/system"

flannel_iface: "eth0"

#calico_iface: ""
calico_ebpf: ""
calico_cidr: ""
calico_tag: ""

apiserver_endpoint: ""

k3s_token: "NA"

extra_server_args: ""
extra_agent_args: ""

kube_vip_tag_version: "v0.7.1"

kube_vip_cloud_provider_tag_version: ""
kube_vip_lb_ip_range: ""

metal_lb_speaker_tag_version: "v0.13.12"
metal_lb_controller_tag_version: "v0.13.12"

metal_lb_ip_range: ""
```

### Hosts

`host.ini`

```ini
[master]
IP.ADDRESS.ONE

[node]
IP.ADDRESS.TWO
IP.ADDRESS.THREE

[k3s_cluster:children]
master
node
```

## Possible Solution

- [x] I've checked the [General Troubleshooting Guide](https://github.com/techno-tim/k3s-ansible/discussions/20)
