### ISSUE TITLE
Unstable VIP PING & K3S too new for Rancher

### ISSUE THREAD

**Issue by teknowill** [techno-tim/k3s-ansible#47]
this link gets a 404, but i did the k3s trouble shooting check list, 
https://github.com/techno-tim/k3s-ansible/discussions/20

I was able to get this working with a older release 
with most current I get:

unstable Ping VIP IP#
K3S  need to be < v1.24 for Rancher

## Expected Behavior

VIP end point ping should be stable
Helm should be able to deploy Rancher with documented commands

## Current Behavior

You can ping the VIP/API IP# intermittently , so get node and helm deployments are hit or miss
Rancher Deployment will fail because K3S is > 1.24

## Steps to Reproduce

1. deploy with code base that had all.yml Commits on May 26, 2022, 3 etcd control, 5 workers Proxmox VM
 (across there physical nodes)
2. deploy longhorn in default space, shared with workers (just learning the process)
3. deploy minecraft > everything was stable for weeks, though it kept over poding one node
4. backup, take down minecraft and longhorn
5. reset
6. git pull on 8/1/22, use latest
which has changes to, all.yml, main.yml, metallb configmap metallb ipaddresspool, metallb yamls, vip rbac, vip yaml
7. add 3 VM for dedicated longhorn > verify ansible can apt update and install proxmox guest agent and can password less ssh
8. add 3x IP# under nodes (3 control, 5 workers, 3 worker for longhorn only)
9.  deploy with 8/1/22 version

## Context (variables)

Operating system: Ubuntu 22

Hardware: 2x dual xeon nodes, 48 thread, 256GB Ram, 1x 1 liter node with a i5 10th 64GB Ram

### Variables Used:
I didn't alter these, save adding my own token and IP#
 they are what have been listed in the repo 

`all.yml`

```yml
k3s_version: "1.24"
ansible_user: NA
systemd_dir: ""

flannel_iface: ""

apiserver_endpoint: ""

k3s_token: "NA"

extra_server_args: ""
extra_agent_args: ""

kube_vip_tag_version: ""

metal_lb_speaker_tag_version: ""
metal_lb_controller_tag_version: ""

metal_lb_ip_range: ""
```

### Hosts 

`host.ini`

```ini
[master]
IP.ADDRESS.ONE
IP.ADDRESS.TWO
IP.ADDRESS.THREE

[node]
IP.ADDRESS.FOUR
IP.ADDRESS.FIVE

[k3s_cluster:children]
master
node
```

## Possible Solution

It seems to deploy ok, just something isn't quite the same when it comes to the VIP/API IP# access
From what I can the version changes are very particular 

I tried taking various nodes offline one at a time, this didn't really help in any repeatable way. So I don't think it's any one node/vm or it's physical networking

tried just going to a older k3s , which might of helped rancher, but didn't help vip/metallb.
I'll try to see if I can find a vip or metallb log file (but I don't really know vip or metallb)

for now, going to try reversing the pull request and deployment with older stack
