### ISSUE TITLE
MetalLB AddressPool and L2Advertisement is not applied

### ISSUE THREAD

**Issue by devantler** [techno-tim/k3s-ansible#56]
When I run the ansible-playbook, the metallb address pool and l2advertisement are not applied. I had to create these manifest files and apply them to fix my issue:

```yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.10.10.10-10.10.10.20
```

```yaml
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
```

## Expected Behavior

I would expect all manifest in the ansible roles to be applied.

## Current Behavior

I think all but the address pool and l2advertisement get applied; not sure if this applies to other manifests as well. It might be related to the latest change where manifests are removed as part of the cleanup. But I am new to this ansible-playbook so I cannot verify that.

## Steps to Reproduce

1. Add and configure `my_cluster/hosts.ini`
1. Add and configure `my_cluster/group_vars/all.yml`
2. Run `bash deploy.sh` to execute the ansible playbook.
3. Wait till finished
4. Check `kubectl get IPAddressPool -A` and `kubectl get L2Advertisement -A` to see that neither exists.

## Context (variables)

Operating system:

3x Ubuntu 22.04 Server

Hardware:

3x Raspberry Pi 4B

### Variables Used

`all.yml`

```yaml
k3s_version: v1.24.3+k3s1
# this is the user that has ssh access to these machines
ansible_user: devantler
systemd_dir: /etc/systemd/system

# Set your timezone
system_timezone: "Europe/Copenhagen"

# interface which will be used for flannel
flannel_iface: "eth0"

# apiserver_endpoint is virtual ip-address which will be configured on each master
apiserver_endpoint: "10.10.10.0"

# k3s_token is required  masters can talk together securely
# this token should be alpha numeric only
k3s_token: "i-will-keep-this-secret"

# change these to your liking, the only required one is--disable servicelb
extra_server_args: "--disable servicelb --disable traefik"
extra_agent_args: ""

# image tag for kube-vip
kube_vip_tag_version: "v0.5.0"

# image tag for metal lb
metal_lb_speaker_tag_version: "v0.13.4"
metal_lb_controller_tag_version: "v0.13.4"

# metallb ip range for load balancer
metal_lb_ip_range: "10.10.10.10-10.10.10.20"
```

### Hosts

`host.ini`

```ini
[master]
10.10.10.1
10.10.10.2
10.10.10.3

[k3s_cluster:children]
master
```

Might also be related to this. I want a HA setup with three nodes, so all my nodes should be masters. Is this supported? If not, can it be supported?
