### ISSUE TITLE
k3s agent stuck on HA env 

### ISSUE THREAD

**Issue by alfredodeluca** [techno-tim/k3s-ansible#594]
## Expected Behavior

On HA env I would expect 2 master e 2 node running smoothly.

## Current Behavior
it seems that 2 worker nodes are stuck with the following logs entries
**Oct 15 12:46:43 ubumba01 k3s[1596]: time="2024-10-15T12:46:43+02:00" level=error msg="failed to get CA certs: Get \"https://127.0.0.1:6444/cacerts\": read tcp 127.0.0.1:43760->127.0.0.1:6444: read: connection reset by peer"**

## Steps to Reproduce

1. 2 master in HA
2. 2 workers nodes
3.
4.

## Context (variables)

Operating system:  mix of Debian and Ubuntu 

Hardware: mix of laptop

### Variables Used

`all.yml`

```yml
k3s_version: ""
ansible_user: NA
systemd_dir: ""

flannel_iface: ""

#calico_iface: ""
calico_ebpf: ""
calico_cidr: ""
calico_tag: ""

apiserver_endpoint: ""

k3s_token: "NA"

extra_server_args: ""
extra_agent_args: ""

kube_vip_tag_version: ""

kube_vip_cloud_provider_tag_version: ""
kube_vip_lb_ip_range: ""

metal_lb_speaker_tag_version: ""
metal_lb_controller_tag_version: ""

metal_lb_ip_range: ""
```

### Hosts

`host.ini`

```ini
master]
10.116.1.22 
10.116.1.233

[node]
10.116.1.189 
10.116.1.27  

[k3s_cluster:children]
master
node
```

## Possible Solution

- [x] I've checked the [General Troubleshooting Guide](https://github.com/techno-tim/k3s-ansible/discussions/20)
