### ISSUE TITLE
Took Master 1 Offline VIP Didn't Failover

### ISSUE THREAD

**Issue by HomeLabRedneck** [techno-tim/k3s-ansible#602]
## Expected Behavior

Master 2 or 3 should have picked up the VIP

## Current Behavior

VIP is unpingable and getting this error when trying to interact with the cluster. 

E1028 08:12:17.626212    8298 memcache.go:265] couldn't get current server API group list: the server is currently unable to handle the request
Error from server (ServiceUnavailable): the server is currently unable to handle the request

## Steps to Reproduce

1. Set up follow the guide
2. Turn off Master 1
3. 
4.

## Context (variables)

Everything else was left to default

Operating system:
Ubuntu 24.10

Hardware:
SuperMicro server

### Variables Used

`all.yml`

```yml
k3s_version: "v1.30.2+k3s2"
ansible_user: NA
systemd_dir: "/etc/systemd/system"

flannel_iface: "ens18"

#calico_iface: ""
calico_ebpf: ""
calico_cidr: ""
calico_tag: ""

apiserver_endpoint: ""

k3s_token: "NA"

extra_server_args: ""
extra_agent_args: ""

kube_vip_tag_version: "v0.8.2"

kube_vip_cloud_provider_tag_version: ""
kube_vip_lb_ip_range: ""

metal_lb_speaker_tag_version: "v0.14.8"
metal_lb_controller_tag_version: "v0.14.8"

metal_lb_ip_range: "10.0.110.234-10.0.110.254"
```

### Hosts

`host.ini`

```ini
[master]
10.0.110.21
10.0.110.22
10.0.110.23

[node]
10.0.110.24
10.0.110.25

[k3s_cluster:children]
master
node
```

## Possible Solution

- [ ] I've checked the [General Troubleshooting Guide](https://github.com/techno-tim/k3s-ansible/discussions/20)
