### ISSUE TITLE
Automatic dependency tag upgrades

### ISSUE THREAD

**Issue by 4t1l4** [techno-tim/k3s-ansible#608]
## Expected Behavior

Dependency tags are kept up to date with some automated process.

## Current Behavior

Tags in some variables in places like the [sample inventory](https://github.com/techno-tim/k3s-ansible/blob/master/inventory/sample/group_vars/all.yml#L16) are not updated automatically and this is not a chore worth a human's time.

## Steps to Reproduce

1. A dependency upstream is updated, like MetalLB controller.
2. The default tag for it is not updated.
3. Someone will have to notice and commit a change with the updated tag.

## Context (variables)

Operating system: All

Hardware: All

### Variables Used

`all.yml`

```yml
k3s_version: ""

calico_tag: ""

kube_vip_tag_version: ""

metal_lb_speaker_tag_version: ""
metal_lb_controller_tag_version: ""

```

### Hosts

Not relevant.

## Possible Solution

I haven't found a solution using Dependabot,  but I am happy to submit a PR with the needed changes to let Renovate do this. It's a hobby of mine to get people onboard Renovate, I'm not associated in any way with them, just love how easy they made my life maintaining projects.

- [ x] I've checked the [General Troubleshooting Guide](https://github.com/techno-tim/k3s-ansible/discussions/20)
