### ISSUE TITLE
Spelling error on kube-vip bgp mode

### ISSUE THREAD

**Issue by Qwiko** [techno-tim/k3s-ansible#633]
When using kube-vip in bgp mode with multiple bgp peers using: kube_vip_bgp_peers variable it does not work due to this error.

[Line here:](https://github.com/techno-tim/k3s-ansible/blob/422621c69cdc7f57381dadaf6c26c8b3f4ff447a/roles/k3s_server/templates/vip.yaml.j2#L65C17-L65C25)
```yaml
{% if _kube_vip_bgp_peers | length > 0 %}
        - name: bgppeers <- This variable here
          value: "{{ _kube_vip_bgp_peers | map(attribute='peer_address') | zip(_kube_vip_bgp_peers| map(attribute='peer_asn')) | map('join', ',') | join(':') }}"  # yamllint disable-line rule:line-length
{% else %}
```

This should be according to: https://kube-vip.io/docs/installation/flags/#environment-variables bgp_peers, not bgppeers.

**Comment by Qwiko** [comment]
It appears the line is joined incorrectly as well.

My example renders like this: 192.168.0.1,65001:192.168.11.1,65002
But should be the other way round: 192.168.0.1:65001,192.168.11.1:65002

Also this piece of code should not 'else' bgp_as. It should be before the bgp_peers section.

```yaml
{% if _kube_vip_bgp_peers | length > 0 %}
        - name: bgppeers
          value: "{{ _kube_vip_bgp_peers | map(attribute='peer_address') | zip(_kube_vip_bgp_peers| map(attribute='peer_asn')) | map('join', ',') | join(':') }}"  # yamllint disable-line rule:line-length
{% else %}
{% if kube_vip_bgp_as is defined %}
        - name: bgp_as
          value: "{{ kube_vip_bgp_as }}"
{% endif %}
```
